### ISSUE TITLE
How to set different default slider offset and specify value range?

### ISSUE THREAD

**Issue by borrrrring** [guoyingtao/Inchworm#2]
Thx a lot to providing so wonderful pod, but I have some problems to use. such as set different default slider offset (about pointer and centerDot) and specify value range(such as [0, 100] but not [-100, 100])

**Comment by guoyingtao** [comment]
@borrrrring 
When you specify value range as [0, 100], do you want the pointer in the middle of the view or at the left of the view?
 ____0-----
 ____**|**||||||||||


0 ------100                   
**|**||||||||||||||||||

**Comment by borrrrring** [comment]
0 ------100
|||||||||||||||||||

Thank for your reply, this is what I want like Photo.app shows when value range is [0, 100].

**Comment by guoyingtao** [comment]
Just realized if I put the pointer at the left, it is hard to position icons above the Slider.

Below is the case of  the pointer in the middle of the view
<img width="304" alt="image" src="https://github.com/guoyingtao/Inchworm/assets/26723384/89b47c70-bcd3-46b8-9950-3d25f4538638">

<img width="289" alt="image" src="https://github.com/guoyingtao/Inchworm/assets/26723384/a86a8457-0fa9-4b0a-8b41-4461fe9aa993">

Does it look good to your case?

**Comment by borrrrring** [comment]
Yes, how can do that? Could you please update Example for these? Thanks a lot!

**Comment by guoyingtao** [comment]
@borrrrring 
Can you the check the Example branch in the branch [range-adjust](https://github.com/guoyingtao/Inchworm/tree/range-adjust) and find createHorizontalUnilateralTypeSlider()? I updated the Example project and add more demos.

If it works for you, I can release a new version.

<img width="343" alt="image" src="https://github.com/guoyingtao/Inchworm/assets/26723384/41e763a0-d701-4f30-95db-f1163fd63810">

**Comment by borrrrring** [comment]
Thank you very much for the update, it's very helpful to me. I have a suggestion: instead of using different sliderValueRangeType sliders by creating them, would it be possible to set limitNumber as limitNumbers: Range<Int>, such as (0..<30) or (-40, 40), to automatically change the current slider's sliderValueRangeType? This would be beneficial because some parameters in the modelList are of type BilateralType or UnilateralType.

**Comment by guoyingtao** [comment]
@borrrrring 
Thanks for the suggestion!
I updated code. Can you take a look again to see if it works for you?

**Comment by guoyingtao** [comment]
@borrrrring 
On second thought, I think Range is hard to control the input from users. (For example, a user can input something like -20...40 or 3...33)
I added associated value in SliderValueRangeType
```Swift
public enum SliderValueRangeType {
    case bilateral(limit: Int)
    case unilateral(limit: Int)
}
```

Also I updated ProcessIndicatorModel which use sliderValueRangeType instead of limitNumber

Now each indicator can have its own sliderValueRangeType

**Comment by borrrrring** [comment]
Thank you very much for your help. It is a perfect copy of the slider of Photo.app.

**Comment by guoyingtao** [comment]
@borrrrring 
Great!
I will release a new version later.
I haven't worked on this project for a while, there might be some bugs in it. Welcome more feedback!

**Comment by guoyingtao** [comment]
@borrrrring 
I released Inchworm 1.0.0. You can have a try to see if it works for you.

**Comment by borrrrring** [comment]
Hi, I still have another small confusion, how can I set the default value for a Slider when editing a project again during initialization?
@guoyingtao

**Comment by guoyingtao** [comment]
@borrrrring 
I need to add a new feature to support default value.

**Comment by guoyingtao** [comment]
@borrrrring 
Please check #5 and [this branch](https://github.com/guoyingtao/Inchworm/tree/default-value) to see if it works for you.

**Comment by guoyingtao** [comment]
@borrrrring 
I released Inchworm 1.1.0 which includes this default value feature.
